### ISSUE TITLE
Psamm-import-bigg should keep integers as integers

### ISSUE THREAD

**Issue by spikeliu** [zhanglab/psamm-import#9]
Psamm-import-bigg currently would transform integers into floating numbers, but it should keep integers as integers. for example, running `psamm-import-bigg e_coli_core --dest e_coli_core/` would result in a reaction.yaml with all stoichiometric values transfromed into floating numbers.

**Comment by jonls** [comment]
This seems to be an issues with the `cobrajson` module. We can use the `parse_float` parameter when calling `json.load` in that module to parse numbers as `Decimal` instead of `float`. This is similar to how we currently handle SBML files. The `Decimal` instance can be converted to `int` if it is an integer.
